---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: your-domain
  namespace: default
spec:
  secretName: your-domain-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.yourdomain.co.uk"
  dnsNames:
  - "*.yourdomain.co.uk"
  - yourdomain.co.uk
