---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
type: Opaque
# WARNING! You need an API token, not a Global API key: https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/#api-tokens
stringData:
  cloudflare-token: YOUR-RANDOM-TOKEN 
